@extends('layouts.app')
@section('content')
    @include('partials.hero')
    @include('partials.about')
    @include('partials.portfolio-stack')
    @include('partials.process')
    @include('partials.service')
    @include('partials.faqs-testimonial-socialmedia')
@endsection
