import sharp from 'sharp';
import { readdirSync, mkdirSync, writeFileSync, statSync } from 'fs';
import { join, extname, basename, relative } from 'path';

const INPUT    = './public/img';
const OUTPUT   = './public/img';
const SKIP_DIR = 'optimised';
const LQIP_OUT = './resources/views/partials/lqip.blade.php';

const SUPPORTED = ['.jpg', '.jpeg', '.png', '.webp'];
const lqipMap   = {};

function collect(dir) {
    let files = [];
    for (const entry of readdirSync(dir)) {
        if (entry === SKIP_DIR) continue;
        const full = join(dir, entry);
        if (statSync(full).isDirectory()) {
            files = files.concat(collect(full));
        } else if (SUPPORTED.includes(extname(entry).toLowerCase())) {
            files.push(full);
        }
    }
    return files;
}

const files = collect(INPUT);
console.log(`\nFound ${files.length} images — compressing...\n`);

for (const file of files) {
    const name    = basename(file, extname(file));
    const dir     = file.replace(/\/[^/]+$/, '');
    const outFile = join(dir, `${name}.webp`);
    const rel     = relative('./public', file);

    try {
        await sharp(file)
            .webp({ quality: 82, effort: 6 })
            .toFile(outFile);

        const lqipBuf = await sharp(file)
            .resize(20)
            .webp({ quality: 20 })
            .toBuffer();

        const lqipKey    = rel.replace(/[^a-zA-Z0-9]/g, '_').replace(/_+$/, '');
        lqipMap[lqipKey] = `data:image/webp;base64,${lqipBuf.toString('base64')}`;

        console.log(`✓  ${rel}`);
    } catch (err) {
        console.error(`✗  ${rel} — ${err.message}`);
    }
}

mkdirSync('./resources/views/partials', { recursive: true });

const lines = [
    '{{-- Auto-generated by compress.mjs — do not edit manually --}}',
    '@php',
    '    $lqip = [',
    ...Object.entries(lqipMap).map(([k, v]) => `        '${k}' => '${v}',`),
    '    ];',
    '@endphp',
].join('\n');

writeFileSync(LQIP_OUT, lines);

console.log(`\n✓  lqip.blade.php written → ${LQIP_OUT}`);
console.log(`\nDone. Update your <img> src paths from .jpg/.png → .webp\n`);
